### ISSUE TITLE
How to use in Ionic 

### ISSUE THREAD

**Issue by LucaTrip** [kitolog/cordova-plugin-timer#1]
Hi, I installed this plugin in my Ionic project but I don't understand how to use it. I create instance of socket type `    this.nativeTimer = new window.nativeTimer();
` in my provider and then call the methods `        this.nativeTimer.start(0, duration,
          () => {
    // success
}, (error) => {
    // error
}); 
` to start the interval and `this.nativeTimer.stop()` to stop the interval. But when the start method is invoked return an error **Invalid operation for this timer state: STARTED**. what am I doing wrong?
My info: 

> Ionic:
>    ionic (Ionic CLI)  : 4.8.0
>    Ionic Framework    : ionic-angular 3.9.2
>    @ionic/app-scripts : 3.1.8
> 
> Cordova:
>    cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
>    Cordova Platforms     : android 7.1.4
> 
> System:
>    Android SDK Tools : 26.1.1
>    NodeJS            : v9.2.0
>    npm               : 5.5.1
>    OS                : Linux 4.15

**Comment by adirgan1** [comment]
How did you find out how to use it on Ionic
